## Matrices
orden de una matriz 
[A]3*2=N SON TRES FILAS Y DOS COLUMNAS

      (a11   a12   aa13)      
[A]2*3 (a21    a22   a23)


[M]2*3= (2   4   7)
        (-1   0   -3)

[k]1*3=(k11=3/4)

[T]=3*3; t32=9

## igualdad de matrices
dos matrices son iguales si y solo si 
aij=bij
entonces se cumple que a11=b11 son iguales y asi sucesivamente 

### son estas matrices iguales ?
[F]=(5,6  2,1  0,3)
    (4,8  1,9  3,7)

[G]=(5,6   2,1)
    (4,8   1,9)

[H]=(5,8   2,1   0,3)
    (4,8   1,9   2,7)
#### entonces f y g no son lo mismo porque son distintas en orden y f con h aunque tengan el mismo tamaño f23 y h23 sons distintas 3,7 y 2,7.


## SUMA DE MATRICES
ES TERMINOS POR TERMIONO OSEA a11+b11 o a22+b22 
ejem: /n
[A]=2*2=(1  2)
        (3  4)
[B]=2*2=(2  3)
        (5  4)
[C]=2*2=(3  5)
        (8  8)

In [ ]:
import numpy as np 
elemnt_A = np.array([ ['a11','a12'],
              ['a21','a22'],
              ['a31','a32'],
              ['a41','a42']])
A = np.array([ [1,2],
              [3,4],
              [5,6],
              [7,8]])
print(elemnt_A)  
print (F'A(4X2)= \n{A}')
print (f' el elemto a32 es igual a',A[2,1])

[['a11' 'a12']
 ['a21' 'a22']
 ['a31' 'a32']
 ['a41' 'a42']]
A(4X2)= 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
 el elemto a32 es igual a 2


## Suma de matrices 

In [13]:
A = np.array([ [1,2],
              [3,4],
              [5,6]])

B = np.array([ [1,2],
              [3,4],
              [5,6]])
C = A+B 
print (f'C(3x2)\n {C}' )

C(3x2)
 [[ 2  4]
 [ 6  8]
 [10 12]]


Las matrices $A$ y $B$ representan las ventas en dos años, en millones de dólares, de los tres productos de una empresa en las cuatro regiones en que está disponible. Es decir, $a_{ij}$ y $b_{ij}$ representan el monto de las ventas del producto $i$ en la región $j$ el primer y segundo año, respectivamente:

<br>

\begin{split}
A = \begin{pmatrix}
 2,6 &  4,8 &  1,8 & 0,9 \\
 3,2 &  4,4 &  2,5 & 2,8 \\
 2,4 &  3,6 &  3,8 & 2,5 \\
\end{pmatrix} \text{ } B= \begin{pmatrix}
 3,6 &  2,5 &  3,0 & 2,5 \\
 4,5 &  5,0 &  3,5 & 3,8 \\
 2,9 &  3,0 &  4,6 & 4,0 \\
\end{pmatrix}
\end{split}

<br>

1. Indique el orden de cada matriz.
2. Calcule la matriz $S = A + B$.
3. Calcule la matriz $D = B - A$.
4. Indique el valor e interprete los elementos $s_{24}$ y $d_{24}$.
5. Para el tercer año de funcionamiento, los tres productos ahora están disponibles en seis regiones. Durante este año, las ventas de esta empresa estarán registradas en una matriz $E$. ¿Es posible determinar la matriz $T = A + B + E$? Justifique su respuesta.

In [35]:

# REGION        1      2   3       4 
A = np.array([[2.6 , 4.8 , 1.8 , 0.9], # producto 1 
             [3.2 , 4.4 , 2.5 , 2.8],  # producto 2
             [2.4 , 3.6 , 3.8 , 2.5]])  # producto 3

B = np.array([[3.6,2.5,3.0,2.5],
             [4.5,5.0,3.5,3.8],
             [2.9,3.0,4.6,4.0]])
S = A + B
D = B - A
print (f'S(3x4) =  \n {S}')
print (f'el total de las ventas en los dos años del producto 2 en la region 4 es  s24 = {S[1,3]} mill dolares ')
print(f'D(3x4= \n {D}')
print (f'el AUMENTO  de las ventas en los dos años del producto 2 en la region 4 es  S24 = {D[1,3]} mill dolares ')

print (f'LA DISMINUCION   de las ventas en EL 2DO AÑO RESPECTO AL PRIMERO  en la region 2 es  D32 = {D[2,1]:.1f} mill dolares ')


S(3x4) =  
 [[6.2 7.3 4.8 3.4]
 [7.7 9.4 6.  6.6]
 [5.3 6.6 8.4 6.5]]
el total de las ventas en los dos años del producto 2 en la region 4 es  s24 = 6.6 mill dolares 
D(3x4= 
 [[ 1.  -2.3  1.2  1.6]
 [ 1.3  0.6  1.   1. ]
 [ 0.5 -0.6  0.8  1.5]]
el AUMENTO  de las ventas en los dos años del producto 2 en la region 4 es  S24 = 1.0 mill dolares 
LA DISMINUCION   de las ventas en EL 2DO AÑO RESPECTO AL PRIMERO  en la region 2 es  D32 = -0.6 mill dolares 


# multiplicacion de matrices 
si se puede multiplicar si solo las columnas de A son igual al numero de filas de B


In [ ]:
import numpy as np 
A= np.array([[0,0,0,0],
             [1,2,3,4]])
B= np.array([[0,0,1],
             [0,0,2],
             [0,0,3],
             [0,0,4]])
#A (2x4)*B(4x3)=C(2x3)
# elemen_c=(c11,c12,c13)
#          (c21,c23,cc23)
# c23=1*1+2*2+3*3+4*4
C=A@B
print('la matriz resultantees c(2x3)=')
print(C)
c23=C[1,2]
print(f' el elemto de c23 es= ',{c23})
